"""ORM models for session-extracted follow-ups and roadmap items.

Design decision — RoadmapItem vs SessionFollowup:
  The native app's MemberRoadmapScreen needs a persistent, member-facing list
  of goals/tasks that survives across multiple sessions.  SessionFollowup rows
  ARE the canonical source of truth (they carry full provenance: session_id,
  auto_created, confirmed_by, etc.).  Rather than duplicating rows into a
  separate RoadmapItem table we add a ``show_on_roadmap`` flag directly on
  SessionFollowup.  The roadmap endpoint queries
  ``WHERE show_on_roadmap = TRUE AND member_id = :mid`` and sorts by priority /
  due_date — giving the app its sorted goal list without a second table.

  If a future phase needs roadmap items that are NOT derived from a session
  (e.g. manually added by a care coordinator), introduce a RoadmapItem model
  at that point.  For now, one table keeps migrations and sync logic simple.
"""

import uuid
from datetime import date, datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class SessionFollowup(Base):
    """A single structured item extracted from a completed session transcript.

    Rows are generated by the LLM extraction pass (``auto_created=True``) or
    manually added by CHW/member (``auto_created=False``).  Only one extraction
    pass per session is allowed — idempotency is enforced at the service layer
    by checking ``SessionDocumentation.followups_extracted_at``.

    HIPAA note: ``description`` is PHI and must never be written to structured
    logs.  Log only ``id``, ``session_id``, and ``kind``.
    """

    __tablename__ = "session_followups"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    # ── Ownership / context ───────────────────────────────────────────────────
    # session_id + chw_id are NULLABLE for member-self-set roadmap goals
    # (POST /api/v1/member/roadmap). All LLM-extracted and CHW-session-derived
    # rows have non-NULL values for both. CHW-attributed analytics must filter
    # with WHERE chw_id IS NOT NULL. See migration n6j9k0l1m2n3.
    session_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("sessions.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    member_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=False,
        index=True,
    )
    chw_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=True,
    )

    # ── Classification ────────────────────────────────────────────────────────
    # kind: action_item | follow_up_task | resource_referral | member_goal
    kind: Mapped[str] = mapped_column(String(50), nullable=False, index=True)

    # description: PHI — never log the value
    description: Mapped[str] = mapped_column(Text, nullable=False)

    # owner: chw | member | both — who is responsible for this item
    owner: Mapped[str | None] = mapped_column(String(20))

    # vertical mirrors Session.vertical for easy roadmap filtering without joins
    vertical: Mapped[str | None] = mapped_column(String(50))

    # priority: low | medium | high
    priority: Mapped[str | None] = mapped_column(String(20))

    # due_date: calendar date the item should be completed by
    due_date: Mapped[date | None] = mapped_column()

    # ── Status lifecycle ──────────────────────────────────────────────────────
    # pending → confirmed | dismissed → completed
    status: Mapped[str] = mapped_column(String(20), default="pending", index=True)

    # ── Provenance ────────────────────────────────────────────────────────────
    auto_created: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    confirmed_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=True,
    )
    confirmed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ── Roadmap surface flag ──────────────────────────────────────────────────
    # True when this item should appear on MemberRoadmapScreen.
    # Set to True automatically for items where owner = 'member' or 'both'.
    show_on_roadmap: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
